// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAgentinfo = "agentinfo"

// Agentinfo mapped from table <agentinfo>
type Agentinfo struct {
	Aid        uint32  `gorm:"column:aid;type:int(10) unsigned;primaryKey;uniqueIndex:aid,priority:1;comment:admin ID" json:"aid"` // admin ID
	Level      uint32  `gorm:"column:level;type:tinyint(3) unsigned;not null;default:1" json:"level"`
	Yqcode     string  `gorm:"column:yqcode;type:char(6);not null" json:"yqcode"`
	Name       string  `gorm:"column:name;type:varchar(100);not null" json:"name"`
	Wxname     string  `gorm:"column:wxname;type:varchar(100);not null" json:"wxname"`
	Mobile     string  `gorm:"column:mobile;type:varchar(255);not null" json:"mobile"`
	Createtime string  `gorm:"column:createtime;type:char(10);not null;default:0" json:"createtime"`
	Pid        uint32  `gorm:"column:pid;type:int(10) unsigned;not null;comment:上级代理ID" json:"pid"` // 上级代理ID
	UID        uint32  `gorm:"column:uid;type:int(10) unsigned;not null;comment:玩家ID" json:"uid"`   // 玩家ID
	Commission float64 `gorm:"column:commission;type:decimal(30,2) unsigned;default:0.00" json:"commission"`
	Score      uint64  `gorm:"column:score;type:bigint(20) unsigned" json:"score"`
}

// TableName Agentinfo's table name
func (*Agentinfo) TableName() string {
	return TableNameAgentinfo
}
