// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameBankname = "bankname"

// Bankname mapped from table <bankname>
type Bankname struct {
	TypeID   int32  `gorm:"column:typeId;type:int(11);primaryKey;autoIncrement:true" json:"typeId"`
	BankName string `gorm:"column:bankName;type:char(30);not null" json:"bankName"`
}

// TableName Bankname's table name
func (*Bankname) TableName() string {
	return TableNameBankname
}
