// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameConfig = "config"

// Config mapped from table <config>
type Config struct {
	ID    uint32 `gorm:"column:id;type:int(10) unsigned;primaryKey;autoIncrement:true" json:"id"`
	Name  string `gorm:"column:name;type:varchar(100);not null" json:"name"`
	Value string `gorm:"column:value;type:text;not null" json:"value"`
	Flag  string `gorm:"column:flag;type:varchar(100);not null;uniqueIndex:flag,priority:1" json:"flag"`
	Desc  string `gorm:"column:desc;type:varchar(255)" json:"desc"`
}

// TableName Config's table name
func (*Config) TableName() string {
	return TableNameConfig
}
