// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameControlUser = "control_user"

// ControlUser mapped from table <control_user>
type ControlUser struct {
	UID    int32   `gorm:"column:uid;type:int(5);primaryKey" json:"uid"`
	Chance float64 `gorm:"column:chance;type:double(20,10)" json:"chance"`
}

// TableName ControlUser's table name
func (*ControlUser) TableName() string {
	return TableNameControlUser
}
