// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDiamondChangelog = "diamond_changelog"

// DiamondChangelog mapped from table <diamond_changelog>
type DiamondChangelog struct {
	ID             int32     `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`
	Userid         int32     `gorm:"column:userid;type:int(20);primaryKey" json:"userid"`
	DiamondBefore  int32     `gorm:"column:diamond_before;type:int(20);not null" json:"diamond_before"`
	DiamondChange  int32     `gorm:"column:diamond_change;type:int(20);not null" json:"diamond_change"`
	DiamondCurrent int32     `gorm:"column:diamond_current;type:int(20);not null" json:"diamond_current"`
	ChangeType     int32     `gorm:"column:change_type;type:int(5);not null;comment:0网站加分,1捕鸟,2连线,3赠送,4兑换,528game,6领取,7东山再起,8红包,9八搭二,10牛牛" json:"change_type"` // 0网站加分,1捕鸟,2连线,3赠送,4兑换,528game,6领取,7东山再起,8红包,9八搭二,10牛牛
	ChangeTime     time.Time `gorm:"column:change_time;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"change_time"`
	IsOnline       bool      `gorm:"column:isOnline;type:tinyint(1)" json:"isOnline"`
}

// TableName DiamondChangelog's table name
func (*DiamondChangelog) TableName() string {
	return TableNameDiamondChangelog
}
