// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDongshanzaiqi = "dongshanzaiqi"

// Dongshanzaiqi mapped from table <dongshanzaiqi>
type Dongshanzaiqi struct {
	UserID int32     `gorm:"column:userId;type:int(11);primaryKey" json:"userId"`
	Dcount int32     `gorm:"column:dcount;type:int(1)" json:"dcount"`
	Dtime  time.Time `gorm:"column:dtime;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"dtime"`
}

// TableName Dongshanzaiqi's table name
func (*Dongshanzaiqi) TableName() string {
	return TableNameDongshanzaiqi
}
