// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDowncoinlog = "downcoinlog"

// Downcoinlog mapped from table <downcoinlog>
type Downcoinlog struct {
	ID       int32     `gorm:"column:id;type:int(20);primaryKey;autoIncrement:true" json:"id"`
	UserID   int32     `gorm:"column:userId;type:int(11);not null" json:"userId"`
	MatchID  int32     `gorm:"column:MatchId;type:int(20);comment:场次ID" json:"MatchId"` // 场次ID
	DownCoin int32     `gorm:"column:downCoin;type:int(11);not null" json:"downCoin"`
	WinCoin  int32     `gorm:"column:winCoin;type:int(11);not null" json:"winCoin"`
	Open2    int32     `gorm:"column:open2;type:int(11)" json:"open2"`
	Open3    int32     `gorm:"column:open3;type:int(11)" json:"open3"`
	Open4    int32     `gorm:"column:open4;type:int(11)" json:"open4"`
	Tax      int32     `gorm:"column:tax;type:int(9)" json:"tax"`
	IsBanker bool      `gorm:"column:isBanker;type:tinyint(1);not null" json:"isBanker"`
	ServerID int32     `gorm:"column:serverId;type:int(3);not null;default:1" json:"serverId"`
	Tableid  int32     `gorm:"column:tableid;type:int(3);not null" json:"tableid"`
	Adddate  time.Time `gorm:"column:Adddate;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"Adddate"`
	Mark     bool      `gorm:"column:mark;type:tinyint(1);not null" json:"mark"`
}

// TableName Downcoinlog's table name
func (*Downcoinlog) TableName() string {
	return TableNameDowncoinlog
}
