// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFanyong = "fanyong"

// Fanyong mapped from table <fanyong>
type Fanyong struct {
	Aid        uint32  `gorm:"column:aid;type:int(10) unsigned;primaryKey" json:"aid"`
	Usernum    uint32  `gorm:"column:usernum;type:int(10) unsigned;not null" json:"usernum"`
	Czfee      float64 `gorm:"column:czfee;type:decimal(30,2) unsigned;not null;default:0.00" json:"czfee"`
	Kuifee     float64 `gorm:"column:kuifee;type:decimal(30,2);not null;default:0.00" json:"kuifee"`
	Yufee      float64 `gorm:"column:yufee;type:decimal(30,2) unsigned;not null;default:0.00" json:"yufee"`
	Createtime string  `gorm:"column:createtime;type:char(10);not null;default:0" json:"createtime"`
}

// TableName Fanyong's table name
func (*Fanyong) TableName() string {
	return TableNameFanyong
}
