// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameGameGonggao = "game_gonggao"

// GameGonggao mapped from table <game_gonggao>
type GameGonggao struct {
	ID         uint32 `gorm:"column:id;type:int(10) unsigned;primaryKey;autoIncrement:true" json:"id"`
	Txt        string `gorm:"column:txt;type:varchar(255);not null" json:"txt"`
	Status     bool   `gorm:"column:status;type:tinyint(1) unsigned;not null;default:1;comment:0关闭 1显示" json:"status"` // 0关闭 1显示
	Createtime string `gorm:"column:createtime;type:char(10);not null;default:0" json:"createtime"`
	Updatetime string `gorm:"column:updatetime;type:char(10);not null;default:0" json:"updatetime"`
}

// TableName GameGonggao's table name
func (*GameGonggao) TableName() string {
	return TableNameGameGonggao
}
