// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameGetcoin = "getcoin"

// Getcoin mapped from table <getcoin>
type Getcoin struct {
	ID      int32     `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`
	UserID  int32     `gorm:"column:userId;type:int(10);not null" json:"userId"`
	GetCoin int32     `gorm:"column:getCoin;type:int(20);not null" json:"getCoin"`
	Adddate time.Time `gorm:"column:adddate;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"adddate"`
	Mark    bool      `gorm:"column:mark;type:tinyint(1)" json:"mark"`
	Isget   bool      `gorm:"column:isget;type:tinyint(1);comment:是否可以领取" json:"isget"` // 是否可以领取
	Day     int32     `gorm:"column:day;type:int(3);comment:第几天" json:"day"`            // 第几天
}

// TableName Getcoin's table name
func (*Getcoin) TableName() string {
	return TableNameGetcoin
}
