// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameKefuHuifu = "kefu_huifu"

// KefuHuifu mapped from table <kefu_huifu>
type KefuHuifu struct {
	ID     uint32 `gorm:"column:id;type:int(10) unsigned;primaryKey;autoIncrement:true" json:"id"`
	Key    string `gorm:"column:key;type:varchar(255);not null" json:"key"`
	Txt1   string `gorm:"column:txt1;type:text" json:"txt1"`
	Txt2   string `gorm:"column:txt2;type:text" json:"txt2"`
	Value1 string `gorm:"column:value1;type:varchar(255)" json:"value1"`
	Value2 string `gorm:"column:value2;type:varchar(255)" json:"value2"`
	Value3 string `gorm:"column:value3;type:varchar(255)" json:"value3"`
	Value4 string `gorm:"column:value4;type:varchar(255)" json:"value4"`
}

// TableName KefuHuifu's table name
func (*KefuHuifu) TableName() string {
	return TableNameKefuHuifu
}
