// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameKefuMsg = "kefu_msg"

// KefuMsg mapped from table <kefu_msg>
type KefuMsg struct {
	ID         uint32 `gorm:"column:id;type:int(10) unsigned;primaryKey;autoIncrement:true" json:"id"`
	Kfid       uint32 `gorm:"column:kfid;type:int(10) unsigned;not null;index:kfid,priority:1" json:"kfid"`
	Kfname     string `gorm:"column:kfname;type:varchar(255)" json:"kfname"`
	UID        uint32 `gorm:"column:uid;type:int(10) unsigned;not null;index:uid,priority:1" json:"uid"`
	Uname      string `gorm:"column:uname;type:varchar(255)" json:"uname"`
	Msg        string `gorm:"column:msg;type:varchar(255);not null" json:"msg"`
	Createtime string `gorm:"column:createtime;type:char(10);not null" json:"createtime"`
	Type       bool   `gorm:"column:type;type:tinyint(1) unsigned;not null;comment:1user send 2kefu send" json:"type"` // 1user send 2kefu send
}

// TableName KefuMsg's table name
func (*KefuMsg) TableName() string {
	return TableNameKefuMsg
}
