// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameKefuUsergl = "kefu_usergl"

// KefuUsergl mapped from table <kefu_usergl>
type KefuUsergl struct {
	Kfid  uint32 `gorm:"column:kfid;type:int(10) unsigned;not null;index:kfid,priority:1" json:"kfid"`
	UID   uint32 `gorm:"column:uid;type:int(10) unsigned;not null;index:uid,priority:1" json:"uid"`
	Uname string `gorm:"column:uname;type:varchar(255)" json:"uname"`
}

// TableName KefuUsergl's table name
func (*KefuUsergl) TableName() string {
	return TableNameKefuUsergl
}
