// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLotterylog6005 = "lotterylog_6005"

// Lotterylog6005 mapped from table <lotterylog_6005>
type Lotterylog6005 struct {
	ID          int32     `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`
	Userid      uint32    `gorm:"column:userid;type:int(10) unsigned;not null" json:"userid"`
	ResultArray string    `gorm:"column:result_array;type:text;not null" json:"result_array"`
	LotteryTime time.Time `gorm:"column:lotteryTime;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"lotteryTime"`
}

// TableName Lotterylog6005's table name
func (*Lotterylog6005) TableName() string {
	return TableNameLotterylog6005
}
