// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLotterylog115 = "lotterylog_115"

// Lotterylog115 mapped from table <lotterylog_115>
type Lotterylog115 struct {
	ID               int32     `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`
	Userid           int32     `gorm:"column:userid;type:int(20);not null" json:"userid"`
	Bet              int32     `gorm:"column:bet;type:int(20);not null" json:"bet"`
	LineS            int32     `gorm:"column:line_s;type:int(2);not null" json:"line_s"`
	ScoreBefore      int32     `gorm:"column:score_before;type:int(20);not null" json:"score_before"`
	ScoreLinescore   int32     `gorm:"column:score_linescore;type:int(20);not null" json:"score_linescore"`
	ScoreWin         int32     `gorm:"column:score_win;type:int(20);not null" json:"score_win"`
	ScoreCurrent     int32     `gorm:"column:score_current;type:int(20);not null" json:"score_current"`
	FreeCountBefore  int32     `gorm:"column:free_count_before;type:int(4);not null" json:"free_count_before"`
	FreeCountWin     int32     `gorm:"column:free_count_win;type:int(4);not null" json:"free_count_win"`
	FreeCountCurrent int32     `gorm:"column:free_count_current;type:int(4);not null" json:"free_count_current"`
	ResultArray      string    `gorm:"column:result_array;type:text" json:"result_array"`
	LotteryTime      time.Time `gorm:"column:lotteryTime;type:timestamp;default:CURRENT_TIMESTAMP" json:"lotteryTime"`
	Mark             bool      `gorm:"column:mark;type:tinyint(1)" json:"mark"`
}

// TableName Lotterylog115's table name
func (*Lotterylog115) TableName() string {
	return TableNameLotterylog115
}
