// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLotterylog1001 = "lotterylog_1001"

// Lotterylog1001 mapped from table <lotterylog_1001>
type Lotterylog1001 struct {
	ID          int32     `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`
	ResultArray string    `gorm:"column:result_array;type:text" json:"result_array"`
	LotteryTime time.Time `gorm:"column:lotteryTime;type:timestamp;not null" json:"lotteryTime"`
}

// TableName Lotterylog1001's table name
func (*Lotterylog1001) TableName() string {
	return TableNameLotterylog1001
}
