// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMark = "mark"

// Mark mapped from table <mark>
type Mark struct {
	ID          int64     `gorm:"column:id;type:bigint(20);primaryKey;autoIncrement:true" json:"id"`
	UserID      int32     `gorm:"column:userId;type:int(11);not null" json:"userId"`
	UseCoin     int64     `gorm:"column:useCoin;type:bigint(20);not null" json:"useCoin"`
	WinCoin     int64     `gorm:"column:winCoin;type:bigint(18);not null" json:"winCoin"`
	Tax         int64     `gorm:"column:tax;type:bigint(10);not null" json:"tax"`
	GameID      int32     `gorm:"column:gameId;type:int(5)" json:"gameId"`
	ServerID    int32     `gorm:"column:serverId;type:int(5)" json:"serverId"`
	BalanceTime time.Time `gorm:"column:balanceTime;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"balanceTime"`
	Mark        bool      `gorm:"column:mark;type:tinyint(1)" json:"mark"`
}

// TableName Mark's table name
func (*Mark) TableName() string {
	return TableNameMark
}
