// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameNewsList = "news_list"

// NewsList mapped from table <news_list>
type NewsList struct {
	ID         uint32 `gorm:"column:id;type:int(10) unsigned;primaryKey;autoIncrement:true" json:"id"`
	Cid        uint32 `gorm:"column:cid;type:int(10) unsigned;not null" json:"cid"`
	Title      string `gorm:"column:title;type:varchar(255);not null" json:"title"`
	Content    string `gorm:"column:content;type:text;not null" json:"content"`
	Createtime string `gorm:"column:createtime;type:char(10);not null;default:0" json:"createtime"`
	Updatetime string `gorm:"column:updatetime;type:char(10);not null;default:0" json:"updatetime"`
}

// TableName NewsList's table name
func (*NewsList) TableName() string {
	return TableNameNewsList
}
