// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePaylog = "paylog"

// Paylog mapped from table <paylog>
type Paylog struct {
	ID           uint32  `gorm:"column:id;type:int(10) unsigned;primaryKey;autoIncrement:true" json:"id"`
	UID          uint32  `gorm:"column:uid;type:int(10) unsigned;not null" json:"uid"`
	Fee          float64 `gorm:"column:fee;type:decimal(10,2) unsigned;not null;default:0.00" json:"fee"`
	Type         bool    `gorm:"column:type;type:tinyint(1) unsigned;not null;comment:1：微信支付；2：支付宝" json:"type"` // 1：微信支付；2：支付宝
	Osn          string  `gorm:"column:osn;type:varchar(255);not null" json:"osn"`
	Osnjz        string  `gorm:"column:osnjz;type:varchar(255);not null" json:"osnjz"`
	Createtime   string  `gorm:"column:createtime;type:char(10);not null;default:0" json:"createtime"`
	Paytime      string  `gorm:"column:paytime;type:char(10);not null;default:0" json:"paytime"`
	Status       bool    `gorm:"column:status;type:tinyint(1) unsigned;not null;comment:0待付款  1已付款 2已关闭" json:"status"` // 0待付款  1已付款 2已关闭
	Payresmsg    string  `gorm:"column:payresmsg;type:text" json:"payresmsg"`
	Prepayresmsg string  `gorm:"column:prepayresmsg;type:text" json:"prepayresmsg"`
	Payendtime   string  `gorm:"column:payendtime;type:char(10);not null;default:0" json:"payendtime"`
}

// TableName Paylog's table name
func (*Paylog) TableName() string {
	return TableNamePaylog
}
