// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameRechargelogUser = "rechargelog_user"

// RechargelogUser mapped from table <rechargelog_user>
type RechargelogUser struct {
	ID         uint32 `gorm:"column:id;type:int(10) unsigned;primaryKey;autoIncrement:true" json:"id"`
	Adminid    uint32 `gorm:"column:adminid;type:int(10) unsigned" json:"adminid"`
	Userid     uint32 `gorm:"column:userid;type:int(10) unsigned" json:"userid"`
	Createtime string `gorm:"column:createtime;type:char(10);default:0" json:"createtime"`
	Czfee      uint64 `gorm:"column:czfee;type:bigint(20) unsigned" json:"czfee"`
	Oldfee     uint64 `gorm:"column:oldfee;type:bigint(20) unsigned" json:"oldfee"`
	Newfee     uint64 `gorm:"column:newfee;type:bigint(20) unsigned" json:"newfee"`
	Type       bool   `gorm:"column:type;type:tinyint(1) unsigned;comment:0 -  1 +" json:"type"`    // 0 -  1 +
	Fromtype   uint32 `gorm:"column:fromtype;type:tinyint(3) unsigned;comment:1-5" json:"fromtype"` // 1-5
}

// TableName RechargelogUser's table name
func (*RechargelogUser) TableName() string {
	return TableNameRechargelogUser
}
