// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameRechargelogKefu = "rechargelog_kefu"

// RechargelogKefu mapped from table <rechargelog_kefu>
type RechargelogKefu struct {
	ID         uint32 `gorm:"column:id;type:int(10) unsigned;primaryKey;autoIncrement:true" json:"id"`
	Adminid    uint32 `gorm:"column:adminid;type:int(10) unsigned;not null" json:"adminid"`
	Kefuid     uint32 `gorm:"column:kefuid;type:int(10) unsigned;not null" json:"kefuid"`
	Createtime string `gorm:"column:createtime;type:char(10);not null;default:0" json:"createtime"`
	Czfee      uint64 `gorm:"column:czfee;type:bigint(20) unsigned;not null" json:"czfee"`
	Oldfee     uint64 `gorm:"column:oldfee;type:bigint(20) unsigned;not null" json:"oldfee"`
	Newfee     uint64 `gorm:"column:newfee;type:bigint(20) unsigned;not null" json:"newfee"`
	Type       bool   `gorm:"column:type;type:tinyint(1) unsigned;not null;comment:0 -  1 +" json:"type"` // 0 -  1 +
}

// TableName RechargelogKefu's table name
func (*RechargelogKefu) TableName() string {
	return TableNameRechargelogKefu
}
