// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameRechargelogVideo = "rechargelog_video"

// RechargelogVideo mapped from table <rechargelog_video>
type RechargelogVideo struct {
	ID         uint32 `gorm:"column:id;type:int(10) unsigned;primaryKey;autoIncrement:true" json:"id"`
	Adminid    uint32 `gorm:"column:adminid;type:int(10) unsigned;not null" json:"adminid"`
	Userid     uint32 `gorm:"column:userid;type:int(10) unsigned;not null" json:"userid"`
	Createtime string `gorm:"column:createtime;type:char(10);not null;default:0" json:"createtime"`
	Czfee      uint64 `gorm:"column:czfee;type:bigint(20) unsigned;not null" json:"czfee"`
	Oldfee     uint64 `gorm:"column:oldfee;type:bigint(20) unsigned;not null" json:"oldfee"`
	Newfee     uint64 `gorm:"column:newfee;type:bigint(20) unsigned;not null" json:"newfee"`
	Type       bool   `gorm:"column:type;type:tinyint(1) unsigned;not null;comment:0 -  1 +" json:"type"` // 0 -  1 +
}

// TableName RechargelogVideo's table name
func (*RechargelogVideo) TableName() string {
	return TableNameRechargelogVideo
}
