// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameReturnscorelog = "returnscorelog"

// Returnscorelog mapped from table <returnscorelog>
type Returnscorelog struct {
	ID         uint32 `gorm:"column:id;type:int(10) unsigned;primaryKey;autoIncrement:true" json:"id"`
	Msg        string `gorm:"column:msg;type:varchar(255);not null;comment:订阅接收到信息" json:"msg"` // 订阅接收到信息
	Ret        string `gorm:"column:ret;type:varchar(255);not null;comment:传递接口信息" json:"ret"`  // 传递接口信息
	Createtime string `gorm:"column:createtime;type:char(10);not null;default:0" json:"createtime"`
}

// TableName Returnscorelog's table name
func (*Returnscorelog) TableName() string {
	return TableNameReturnscorelog
}
