// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameReturnscore = "returnscore"

// Returnscore mapped from table <returnscore>
type Returnscore struct {
	ID         uint32 `gorm:"column:id;type:int(10) unsigned;primaryKey;autoIncrement:true" json:"id"`
	Osn        string `gorm:"column:osn;type:varchar(255);not null" json:"osn"`
	Ret        string `gorm:"column:ret;type:varchar(255);not null" json:"ret"`
	UID        uint32 `gorm:"column:uid;type:int(10) unsigned;not null" json:"uid"`
	Createtime string `gorm:"column:createtime;type:char(10);not null;default:0" json:"createtime"`
	Type       bool   `gorm:"column:type;type:tinyint(1) unsigned;not null;comment:0未处理  1已处理" json:"type"` // 0未处理  1已处理
}

// TableName Returnscore's table name
func (*Returnscore) TableName() string {
	return TableNameReturnscore
}
