// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameScoretotallog = "scoretotallog"

// Scoretotallog mapped from table <scoretotallog>
type Scoretotallog struct {
	ID           int32     `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`
	ServeID      int32     `gorm:"column:serve_id;type:int(11);not null" json:"serve_id"`
	Winscore     float32   `gorm:"column:winscore;type:float" json:"winscore"`
	LotteryCount int32     `gorm:"column:lotteryCount;type:int(20)" json:"lotteryCount"`
	CreateTime   time.Time `gorm:"column:CreateTime;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"CreateTime"`
}

// TableName Scoretotallog's table name
func (*Scoretotallog) TableName() string {
	return TableNameScoretotallog
}
