// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSendcoinlog = "sendcoinlog"

// Sendcoinlog mapped from table <sendcoinlog>
type Sendcoinlog struct {
	Userid        int32     `gorm:"column:userid;type:int(10);comment:用户id" json:"userid"`                  // 用户id
	Getcoinuserid int32     `gorm:"column:getcoinuserid;type:int(10);comment:被赠送用户id" json:"getcoinuserid"` // 被赠送用户id
	Sendcoin      int32     `gorm:"column:sendcoin;type:int(20);comment:赠送金额" json:"sendcoin"`              // 赠送金额
	Addtime       time.Time `gorm:"column:addtime;type:timestamp;default:CURRENT_TIMESTAMP" json:"addtime"`
}

// TableName Sendcoinlog's table name
func (*Sendcoinlog) TableName() string {
	return TableNameSendcoinlog
}
