// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTMessage = "t_message"

// TMessage mapped from table <t_message>
type TMessage struct {
	Type    string `gorm:"column:type;type:varchar(32);primaryKey" json:"type"`
	Msg     string `gorm:"column:msg;type:varchar(1024);not null" json:"msg"`
	Version string `gorm:"column:version;type:varchar(32);not null" json:"version"`
}

// TableName TMessage's table name
func (*TMessage) TableName() string {
	return TableNameTMessage
}
