// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTRoom = "t_rooms"

// TRoom mapped from table <t_rooms>
type TRoom struct {
	UUID       string `gorm:"column:uuid;type:char(20);primaryKey;uniqueIndex:uuid,priority:1" json:"uuid"`
	ID         string `gorm:"column:id;type:char(8);not null;uniqueIndex:id,priority:1" json:"id"`
	Genre      int32  `gorm:"column:genre;type:int(11);not null" json:"genre"`
	RoomType   int32  `gorm:"column:room_type;type:int(11);not null" json:"room_type"`
	Scene      string `gorm:"column:scene;type:varchar(128);not null" json:"scene"`
	BaseInfo   string `gorm:"column:base_info;type:varchar(256);not null;default:0" json:"base_info"`
	CreateTime int32  `gorm:"column:create_time;type:int(11);not null" json:"create_time"`
	NumOfTurns int32  `gorm:"column:num_of_turns;type:int(11);not null" json:"num_of_turns"`
	NextButton int32  `gorm:"column:next_button;type:int(11);not null" json:"next_button"`
	UserId0    int32  `gorm:"column:user_id0;type:int(11);not null" json:"user_id0"`
	UserIcon0  string `gorm:"column:user_icon0;type:varchar(128);not null" json:"user_icon0"`
	UserName0  string `gorm:"column:user_name0;type:varchar(32)" json:"user_name0"`
	UserScore0 int32  `gorm:"column:user_score0;type:int(11)" json:"user_score0"`
	UserId1    int32  `gorm:"column:user_id1;type:int(11);not null" json:"user_id1"`
	UserIcon1  string `gorm:"column:user_icon1;type:varchar(128);not null" json:"user_icon1"`
	UserName1  string `gorm:"column:user_name1;type:varchar(32)" json:"user_name1"`
	UserScore1 int32  `gorm:"column:user_score1;type:int(11)" json:"user_score1"`
	UserId2    int32  `gorm:"column:user_id2;type:int(11);not null" json:"user_id2"`
	UserIcon2  string `gorm:"column:user_icon2;type:varchar(128);not null" json:"user_icon2"`
	UserName2  string `gorm:"column:user_name2;type:varchar(32)" json:"user_name2"`
	UserScore2 int32  `gorm:"column:user_score2;type:int(11)" json:"user_score2"`
	UserId3    int32  `gorm:"column:user_id3;type:int(11);not null" json:"user_id3"`
	UserIcon3  string `gorm:"column:user_icon3;type:varchar(128);not null" json:"user_icon3"`
	UserName3  string `gorm:"column:user_name3;type:varchar(32)" json:"user_name3"`
	UserScore3 int32  `gorm:"column:user_score3;type:int(11)" json:"user_score3"`
	UserId4    int32  `gorm:"column:user_id4;type:int(11);not null" json:"user_id4"`
	UserIcon4  string `gorm:"column:user_icon4;type:varchar(128);not null" json:"user_icon4"`
	UserName4  string `gorm:"column:user_name4;type:varchar(32)" json:"user_name4"`
	UserScore4 int32  `gorm:"column:user_score4;type:int(11)" json:"user_score4"`
	UserId5    int32  `gorm:"column:user_id5;type:int(11);not null" json:"user_id5"`
	UserIcon5  string `gorm:"column:user_icon5;type:varchar(128);not null" json:"user_icon5"`
	UserName5  string `gorm:"column:user_name5;type:varchar(32)" json:"user_name5"`
	UserScore5 int32  `gorm:"column:user_score5;type:int(11)" json:"user_score5"`
	UserId6    int32  `gorm:"column:user_id6;type:int(11);not null" json:"user_id6"`
	UserIcon6  string `gorm:"column:user_icon6;type:varchar(128);not null" json:"user_icon6"`
	UserName6  string `gorm:"column:user_name6;type:varchar(32)" json:"user_name6"`
	UserScore6 int32  `gorm:"column:user_score6;type:int(11)" json:"user_score6"`
	UserId7    int32  `gorm:"column:user_id7;type:int(11);not null" json:"user_id7"`
	UserIcon7  string `gorm:"column:user_icon7;type:varchar(128);not null" json:"user_icon7"`
	UserName7  string `gorm:"column:user_name7;type:varchar(32)" json:"user_name7"`
	UserScore7 int32  `gorm:"column:user_score7;type:int(11)" json:"user_score7"`
	UserId8    int32  `gorm:"column:user_id8;type:int(11);not null" json:"user_id8"`
	UserIcon8  string `gorm:"column:user_icon8;type:varchar(128);not null" json:"user_icon8"`
	UserName8  string `gorm:"column:user_name8;type:varchar(32)" json:"user_name8"`
	UserScore8 int32  `gorm:"column:user_score8;type:int(11)" json:"user_score8"`
	IP         string `gorm:"column:ip;type:varchar(16)" json:"ip"`
	Port       int32  `gorm:"column:port;type:int(11)" json:"port"`
}

// TableName TRoom's table name
func (*TRoom) TableName() string {
	return TableNameTRoom
}
