// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTUser = "t_users"

// TUser mapped from table <t_users>
type TUser struct {
	Userid      uint32  `gorm:"column:userid;type:int(11) unsigned;primaryKey;autoIncrement:true;comment:用户ID" json:"userid"`      // 用户ID
	Account     string  `gorm:"column:account;type:varchar(64);not null;uniqueIndex:account,priority:1;comment:账号" json:"account"` // 账号
	Name        string  `gorm:"column:name;type:varchar(32);comment:用户昵称" json:"name"`                                             // 用户昵称
	Sex         int32   `gorm:"column:sex;type:int(1);comment:性别" json:"sex"`                                                      // 性别
	Headimg     string  `gorm:"column:headimg;type:varchar(256);comment:头像" json:"headimg"`                                        // 头像
	Lv          int32   `gorm:"column:lv;type:smallint(6);default:1;comment:用户等级" json:"lv"`                                       // 用户等级
	Exp         int32   `gorm:"column:exp;type:int(11);comment:用户经验" json:"exp"`                                                   // 用户经验
	Coins       float64 `gorm:"column:coins;type:decimal(64,2);default:0.00;comment:用户金币" json:"coins"`                            // 用户金币
	Gems        float64 `gorm:"column:gems;type:decimal(64,2);default:0.00;comment:用户宝石" json:"gems"`                              // 用户宝石
	Roomid      string  `gorm:"column:roomid;type:varchar(8);comment:所在房间号" json:"roomid"`                                         // 所在房间号
	History     string  `gorm:"column:history;type:varchar(4096);not null;comment:历史" json:"history"`                              // 历史
	Yaoqing     int32   `gorm:"column:yaoqing;type:int(11);comment:邀请人" json:"yaoqing"`                                            // 邀请人
	Time        int32   `gorm:"column:time;type:int(10);comment:注册时间" json:"time"`                                                 // 注册时间
	Shareroomid string  `gorm:"column:shareroomid;type:varchar(8)" json:"shareroomid"`
	Robot       int32   `gorm:"column:robot;type:int(1);not null" json:"robot"`
}

// TableName TUser's table name
func (*TUser) TableName() string {
	return TableNameTUser
}
