// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTUsersRechangeRecord = "t_users_rechange_record"

// TUsersRechangeRecord mapped from table <t_users_rechange_record>
type TUsersRechangeRecord struct {
	ID            uint32  `gorm:"column:id;type:int(11) unsigned;primaryKey;autoIncrement:true;comment:序号" json:"id"`    // 序号
	Userid        uint32  `gorm:"column:userid;type:int(11) unsigned;not null;comment:用户" json:"userid"`                 // 用户
	Orderno       string  `gorm:"column:orderno;type:char(20);not null;comment:订单号" json:"orderno"`                      // 订单号
	Money         float64 `gorm:"column:money;type:decimal(10,2) unsigned;not null;comment:充值金额" json:"money"`           // 充值金额
	PayType       string  `gorm:"column:pay_type;type:char(10);not null;comment:充值类型" json:"pay_type"`                   // 充值类型
	Status        int32   `gorm:"column:status;type:tinyint(2);not null;comment:状态(0：新  1：充值成功)" json:"status"`          // 状态(0：新  1：充值成功)
	Time          int32   `gorm:"column:time;type:int(10);not null;comment:充值时间" json:"time"`                            // 充值时间
	Result        string  `gorm:"column:result;type:text;comment:返回值" json:"result"`                                     // 返回值
	NotifyResult  string  `gorm:"column:notify_result;type:text;comment:异步返回值" json:"notify_result"`                     // 异步返回值
	IsAccount     int32   `gorm:"column:is_account;type:tinyint(2);comment:入帐标志（0：默认  1：已入帐  9:异常）" json:"is_account"`   // 入帐标志（0：默认  1：已入帐  9:异常）
	AccountUserid uint32  `gorm:"column:account_userid;type:int(11) unsigned;comment:入帐人（客户的经纪人）" json:"account_userid"` // 入帐人（客户的经纪人）
	AccountResult string  `gorm:"column:account_result;type:text;comment:入帐返回值" json:"account_result"`                   // 入帐返回值
}

// TableName TUsersRechangeRecord's table name
func (*TUsersRechangeRecord) TableName() string {
	return TableNameTUsersRechangeRecord
}
