// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUserinfo = "userinfo"

// Userinfo mapped from table <userinfo>
type Userinfo struct {
	UserID        int32  `gorm:"column:userId;type:int(10);primaryKey" json:"userId"`
	Devid         int32  `gorm:"column:Devid;type:int(10)" json:"Devid"`
	Firstexchange bool   `gorm:"column:firstexchange;type:tinyint(1);default:1" json:"firstexchange"`
	Zhifubao      string `gorm:"column:zhifubao;type:char(50)" json:"zhifubao"`
	ZhifubaoName  string `gorm:"column:zhifubaoName;type:char(10)" json:"zhifubaoName"`
}

// TableName Userinfo's table name
func (*Userinfo) TableName() string {
	return TableNameUserinfo
}
