// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID         uint32  `gorm:"column:id;type:int(11) unsigned;primaryKey;autoIncrement:true" json:"id"`
	Openid     string  `gorm:"column:openid;type:varchar(255);uniqueIndex:openid,priority:1" json:"openid"`
	Account    string  `gorm:"column:account;type:varchar(255)" json:"account"`
	Nickname   string  `gorm:"column:nickname;type:varchar(100)" json:"nickname"`
	Avatar     string  `gorm:"column:avatar;type:varchar(255)" json:"avatar"`
	Score      uint32  `gorm:"column:score;type:int(10) unsigned" json:"score"`
	Diamond    uint32  `gorm:"column:diamond;type:int(10) unsigned" json:"diamond"`
	Jifen      uint32  `gorm:"column:jifen;type:int(10) unsigned" json:"jifen"`
	Yue        float64 `gorm:"column:yue;type:decimal(10,2) unsigned;default:0.00" json:"yue"`
	Createtime string  `gorm:"column:createtime;type:char(10);default:0" json:"createtime"`
	Logintime  string  `gorm:"column:logintime;type:char(10);default:0" json:"logintime"`
	UID        uint32  `gorm:"column:uid;type:int(10) unsigned" json:"uid"`
	Token      string  `gorm:"column:token;type:char(32)" json:"token"`
	Fromtype   bool    `gorm:"column:fromtype;type:tinyint(1) unsigned;default:1;comment:1-5" json:"fromtype"` // 1-5
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
