// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameYuXiaXieClubTableLog = "yu_xia_xie_club_table_log"

// YuXiaXieClubTableLog mapped from table <yu_xia_xie_club_table_log>
type YuXiaXieClubTableLog struct {
	ID        int64     `gorm:"column:id;type:bigint(20);primaryKey;autoIncrement:true" json:"id"`
	UserID    int32     `gorm:"column:user_id;type:int(11);not null;index:user_id,priority:1;comment:用户id" json:"user_id"` // 用户id
	TableDict string    `gorm:"column:table_dict;type:longtext;comment:桌子内游戏信息" json:"table_dict"`                         // 桌子内游戏信息
	AddDate   time.Time `gorm:"column:add_date;type:timestamp;comment:创建时间" json:"add_date"`                               // 创建时间
	ClubID    string    `gorm:"column:club_id;type:varchar(64);not null;comment:俱乐部id" json:"club_id"`                     // 俱乐部id
}

// TableName YuXiaXieClubTableLog's table name
func (*YuXiaXieClubTableLog) TableName() string {
	return TableNameYuXiaXieClubTableLog
}
