// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package la_ba

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/a937wzgl/a937wzgl_models/models/model"
)

func newLotterylog1002(db *gorm.DB, opts ...gen.DOOption) lotterylog1002 {
	_lotterylog1002 := lotterylog1002{}

	_lotterylog1002.lotterylog1002Do.UseDB(db, opts...)
	_lotterylog1002.lotterylog1002Do.UseModel(&model.Lotterylog1002{})

	tableName := _lotterylog1002.lotterylog1002Do.TableName()
	_lotterylog1002.ALL = field.NewAsterisk(tableName)
	_lotterylog1002.ID = field.NewInt32(tableName, "id")
	_lotterylog1002.Userid = field.NewInt32(tableName, "userid")
	_lotterylog1002.Bet = field.NewInt32(tableName, "bet")
	_lotterylog1002.LineS = field.NewInt32(tableName, "line_s")
	_lotterylog1002.ScoreBefore = field.NewInt32(tableName, "score_before")
	_lotterylog1002.ScoreLinescore = field.NewInt32(tableName, "score_linescore")
	_lotterylog1002.ScoreWin = field.NewInt32(tableName, "score_win")
	_lotterylog1002.ScoreCurrent = field.NewInt32(tableName, "score_current")
	_lotterylog1002.FreeCountBefore = field.NewInt32(tableName, "free_count_before")
	_lotterylog1002.FreeCountWin = field.NewInt32(tableName, "free_count_win")
	_lotterylog1002.FreeCountCurrent = field.NewInt32(tableName, "free_count_current")
	_lotterylog1002.ResultArray = field.NewString(tableName, "result_array")
	_lotterylog1002.LotteryTime = field.NewTime(tableName, "lotteryTime")
	_lotterylog1002.Mark = field.NewBool(tableName, "mark")

	_lotterylog1002.fillFieldMap()

	return _lotterylog1002
}

type lotterylog1002 struct {
	lotterylog1002Do

	ALL              field.Asterisk
	ID               field.Int32
	Userid           field.Int32
	Bet              field.Int32
	LineS            field.Int32
	ScoreBefore      field.Int32
	ScoreLinescore   field.Int32
	ScoreWin         field.Int32
	ScoreCurrent     field.Int32
	FreeCountBefore  field.Int32
	FreeCountWin     field.Int32
	FreeCountCurrent field.Int32
	ResultArray      field.String
	LotteryTime      field.Time
	Mark             field.Bool

	fieldMap map[string]field.Expr
}

func (l lotterylog1002) Table(newTableName string) *lotterylog1002 {
	l.lotterylog1002Do.UseTable(newTableName)
	return l.updateTableName(newTableName)
}

func (l lotterylog1002) As(alias string) *lotterylog1002 {
	l.lotterylog1002Do.DO = *(l.lotterylog1002Do.As(alias).(*gen.DO))
	return l.updateTableName(alias)
}

func (l *lotterylog1002) updateTableName(table string) *lotterylog1002 {
	l.ALL = field.NewAsterisk(table)
	l.ID = field.NewInt32(table, "id")
	l.Userid = field.NewInt32(table, "userid")
	l.Bet = field.NewInt32(table, "bet")
	l.LineS = field.NewInt32(table, "line_s")
	l.ScoreBefore = field.NewInt32(table, "score_before")
	l.ScoreLinescore = field.NewInt32(table, "score_linescore")
	l.ScoreWin = field.NewInt32(table, "score_win")
	l.ScoreCurrent = field.NewInt32(table, "score_current")
	l.FreeCountBefore = field.NewInt32(table, "free_count_before")
	l.FreeCountWin = field.NewInt32(table, "free_count_win")
	l.FreeCountCurrent = field.NewInt32(table, "free_count_current")
	l.ResultArray = field.NewString(table, "result_array")
	l.LotteryTime = field.NewTime(table, "lotteryTime")
	l.Mark = field.NewBool(table, "mark")

	l.fillFieldMap()

	return l
}

func (l *lotterylog1002) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := l.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (l *lotterylog1002) fillFieldMap() {
	l.fieldMap = make(map[string]field.Expr, 14)
	l.fieldMap["id"] = l.ID
	l.fieldMap["userid"] = l.Userid
	l.fieldMap["bet"] = l.Bet
	l.fieldMap["line_s"] = l.LineS
	l.fieldMap["score_before"] = l.ScoreBefore
	l.fieldMap["score_linescore"] = l.ScoreLinescore
	l.fieldMap["score_win"] = l.ScoreWin
	l.fieldMap["score_current"] = l.ScoreCurrent
	l.fieldMap["free_count_before"] = l.FreeCountBefore
	l.fieldMap["free_count_win"] = l.FreeCountWin
	l.fieldMap["free_count_current"] = l.FreeCountCurrent
	l.fieldMap["result_array"] = l.ResultArray
	l.fieldMap["lotteryTime"] = l.LotteryTime
	l.fieldMap["mark"] = l.Mark
}

func (l lotterylog1002) clone(db *gorm.DB) lotterylog1002 {
	l.lotterylog1002Do.ReplaceConnPool(db.Statement.ConnPool)
	return l
}

func (l lotterylog1002) replaceDB(db *gorm.DB) lotterylog1002 {
	l.lotterylog1002Do.ReplaceDB(db)
	return l
}

type lotterylog1002Do struct{ gen.DO }

type ILotterylog1002Do interface {
	gen.SubQuery
	Debug() ILotterylog1002Do
	WithContext(ctx context.Context) ILotterylog1002Do
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ILotterylog1002Do
	WriteDB() ILotterylog1002Do
	As(alias string) gen.Dao
	Session(config *gorm.Session) ILotterylog1002Do
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ILotterylog1002Do
	Not(conds ...gen.Condition) ILotterylog1002Do
	Or(conds ...gen.Condition) ILotterylog1002Do
	Select(conds ...field.Expr) ILotterylog1002Do
	Where(conds ...gen.Condition) ILotterylog1002Do
	Order(conds ...field.Expr) ILotterylog1002Do
	Distinct(cols ...field.Expr) ILotterylog1002Do
	Omit(cols ...field.Expr) ILotterylog1002Do
	Join(table schema.Tabler, on ...field.Expr) ILotterylog1002Do
	LeftJoin(table schema.Tabler, on ...field.Expr) ILotterylog1002Do
	RightJoin(table schema.Tabler, on ...field.Expr) ILotterylog1002Do
	Group(cols ...field.Expr) ILotterylog1002Do
	Having(conds ...gen.Condition) ILotterylog1002Do
	Limit(limit int) ILotterylog1002Do
	Offset(offset int) ILotterylog1002Do
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ILotterylog1002Do
	Unscoped() ILotterylog1002Do
	Create(values ...*model.Lotterylog1002) error
	CreateInBatches(values []*model.Lotterylog1002, batchSize int) error
	Save(values ...*model.Lotterylog1002) error
	First() (*model.Lotterylog1002, error)
	Take() (*model.Lotterylog1002, error)
	Last() (*model.Lotterylog1002, error)
	Find() ([]*model.Lotterylog1002, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Lotterylog1002, err error)
	FindInBatches(result *[]*model.Lotterylog1002, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Lotterylog1002) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ILotterylog1002Do
	Assign(attrs ...field.AssignExpr) ILotterylog1002Do
	Joins(fields ...field.RelationField) ILotterylog1002Do
	Preload(fields ...field.RelationField) ILotterylog1002Do
	FirstOrInit() (*model.Lotterylog1002, error)
	FirstOrCreate() (*model.Lotterylog1002, error)
	FindByPage(offset int, limit int) (result []*model.Lotterylog1002, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ILotterylog1002Do
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (l lotterylog1002Do) Debug() ILotterylog1002Do {
	return l.withDO(l.DO.Debug())
}

func (l lotterylog1002Do) WithContext(ctx context.Context) ILotterylog1002Do {
	return l.withDO(l.DO.WithContext(ctx))
}

func (l lotterylog1002Do) ReadDB() ILotterylog1002Do {
	return l.Clauses(dbresolver.Read)
}

func (l lotterylog1002Do) WriteDB() ILotterylog1002Do {
	return l.Clauses(dbresolver.Write)
}

func (l lotterylog1002Do) Session(config *gorm.Session) ILotterylog1002Do {
	return l.withDO(l.DO.Session(config))
}

func (l lotterylog1002Do) Clauses(conds ...clause.Expression) ILotterylog1002Do {
	return l.withDO(l.DO.Clauses(conds...))
}

func (l lotterylog1002Do) Returning(value interface{}, columns ...string) ILotterylog1002Do {
	return l.withDO(l.DO.Returning(value, columns...))
}

func (l lotterylog1002Do) Not(conds ...gen.Condition) ILotterylog1002Do {
	return l.withDO(l.DO.Not(conds...))
}

func (l lotterylog1002Do) Or(conds ...gen.Condition) ILotterylog1002Do {
	return l.withDO(l.DO.Or(conds...))
}

func (l lotterylog1002Do) Select(conds ...field.Expr) ILotterylog1002Do {
	return l.withDO(l.DO.Select(conds...))
}

func (l lotterylog1002Do) Where(conds ...gen.Condition) ILotterylog1002Do {
	return l.withDO(l.DO.Where(conds...))
}

func (l lotterylog1002Do) Order(conds ...field.Expr) ILotterylog1002Do {
	return l.withDO(l.DO.Order(conds...))
}

func (l lotterylog1002Do) Distinct(cols ...field.Expr) ILotterylog1002Do {
	return l.withDO(l.DO.Distinct(cols...))
}

func (l lotterylog1002Do) Omit(cols ...field.Expr) ILotterylog1002Do {
	return l.withDO(l.DO.Omit(cols...))
}

func (l lotterylog1002Do) Join(table schema.Tabler, on ...field.Expr) ILotterylog1002Do {
	return l.withDO(l.DO.Join(table, on...))
}

func (l lotterylog1002Do) LeftJoin(table schema.Tabler, on ...field.Expr) ILotterylog1002Do {
	return l.withDO(l.DO.LeftJoin(table, on...))
}

func (l lotterylog1002Do) RightJoin(table schema.Tabler, on ...field.Expr) ILotterylog1002Do {
	return l.withDO(l.DO.RightJoin(table, on...))
}

func (l lotterylog1002Do) Group(cols ...field.Expr) ILotterylog1002Do {
	return l.withDO(l.DO.Group(cols...))
}

func (l lotterylog1002Do) Having(conds ...gen.Condition) ILotterylog1002Do {
	return l.withDO(l.DO.Having(conds...))
}

func (l lotterylog1002Do) Limit(limit int) ILotterylog1002Do {
	return l.withDO(l.DO.Limit(limit))
}

func (l lotterylog1002Do) Offset(offset int) ILotterylog1002Do {
	return l.withDO(l.DO.Offset(offset))
}

func (l lotterylog1002Do) Scopes(funcs ...func(gen.Dao) gen.Dao) ILotterylog1002Do {
	return l.withDO(l.DO.Scopes(funcs...))
}

func (l lotterylog1002Do) Unscoped() ILotterylog1002Do {
	return l.withDO(l.DO.Unscoped())
}

func (l lotterylog1002Do) Create(values ...*model.Lotterylog1002) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Create(values)
}

func (l lotterylog1002Do) CreateInBatches(values []*model.Lotterylog1002, batchSize int) error {
	return l.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (l lotterylog1002Do) Save(values ...*model.Lotterylog1002) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Save(values)
}

func (l lotterylog1002Do) First() (*model.Lotterylog1002, error) {
	if result, err := l.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Lotterylog1002), nil
	}
}

func (l lotterylog1002Do) Take() (*model.Lotterylog1002, error) {
	if result, err := l.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Lotterylog1002), nil
	}
}

func (l lotterylog1002Do) Last() (*model.Lotterylog1002, error) {
	if result, err := l.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Lotterylog1002), nil
	}
}

func (l lotterylog1002Do) Find() ([]*model.Lotterylog1002, error) {
	result, err := l.DO.Find()
	return result.([]*model.Lotterylog1002), err
}

func (l lotterylog1002Do) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Lotterylog1002, err error) {
	buf := make([]*model.Lotterylog1002, 0, batchSize)
	err = l.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (l lotterylog1002Do) FindInBatches(result *[]*model.Lotterylog1002, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return l.DO.FindInBatches(result, batchSize, fc)
}

func (l lotterylog1002Do) Attrs(attrs ...field.AssignExpr) ILotterylog1002Do {
	return l.withDO(l.DO.Attrs(attrs...))
}

func (l lotterylog1002Do) Assign(attrs ...field.AssignExpr) ILotterylog1002Do {
	return l.withDO(l.DO.Assign(attrs...))
}

func (l lotterylog1002Do) Joins(fields ...field.RelationField) ILotterylog1002Do {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Joins(_f))
	}
	return &l
}

func (l lotterylog1002Do) Preload(fields ...field.RelationField) ILotterylog1002Do {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Preload(_f))
	}
	return &l
}

func (l lotterylog1002Do) FirstOrInit() (*model.Lotterylog1002, error) {
	if result, err := l.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Lotterylog1002), nil
	}
}

func (l lotterylog1002Do) FirstOrCreate() (*model.Lotterylog1002, error) {
	if result, err := l.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Lotterylog1002), nil
	}
}

func (l lotterylog1002Do) FindByPage(offset int, limit int) (result []*model.Lotterylog1002, count int64, err error) {
	result, err = l.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = l.Offset(-1).Limit(-1).Count()
	return
}

func (l lotterylog1002Do) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = l.Count()
	if err != nil {
		return
	}

	err = l.Offset(offset).Limit(limit).Scan(result)
	return
}

func (l lotterylog1002Do) Scan(result interface{}) (err error) {
	return l.DO.Scan(result)
}

func (l lotterylog1002Do) Delete(models ...*model.Lotterylog1002) (result gen.ResultInfo, err error) {
	return l.DO.Delete(models)
}

func (l *lotterylog1002Do) withDO(do gen.Dao) *lotterylog1002Do {
	l.DO = *do.(*gen.DO)
	return l
}
