// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package la_ba

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/a937wzgl/a937wzgl_models/models/model"
)

func newUseraccount(db *gorm.DB, opts ...gen.DOOption) useraccount {
	_useraccount := useraccount{}

	_useraccount.useraccountDo.UseDB(db, opts...)
	_useraccount.useraccountDo.UseModel(&model.Useraccount{})

	tableName := _useraccount.useraccountDo.TableName()
	_useraccount.ALL = field.NewAsterisk(tableName)
	_useraccount.ID = field.NewInt32(tableName, "Id")
	_useraccount.FreeCount = field.NewInt32(tableName, "freeCount")
	_useraccount.AddDate = field.NewTime(tableName, "AddDate")
	_useraccount.LotteryCount = field.NewInt32(tableName, "LotteryCount")
	_useraccount.NFreeIndex = field.NewString(tableName, "nFreeIndex")
	_useraccount.GameDict = field.NewString(tableName, "gameDict")

	_useraccount.fillFieldMap()

	return _useraccount
}

type useraccount struct {
	useraccountDo

	ALL          field.Asterisk
	ID           field.Int32
	FreeCount    field.Int32
	AddDate      field.Time // 创建时间
	LotteryCount field.Int32
	NFreeIndex   field.String
	GameDict     field.String

	fieldMap map[string]field.Expr
}

func (u useraccount) Table(newTableName string) *useraccount {
	u.useraccountDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u useraccount) As(alias string) *useraccount {
	u.useraccountDo.DO = *(u.useraccountDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *useraccount) updateTableName(table string) *useraccount {
	u.ALL = field.NewAsterisk(table)
	u.ID = field.NewInt32(table, "Id")
	u.FreeCount = field.NewInt32(table, "freeCount")
	u.AddDate = field.NewTime(table, "AddDate")
	u.LotteryCount = field.NewInt32(table, "LotteryCount")
	u.NFreeIndex = field.NewString(table, "nFreeIndex")
	u.GameDict = field.NewString(table, "gameDict")

	u.fillFieldMap()

	return u
}

func (u *useraccount) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *useraccount) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 6)
	u.fieldMap["Id"] = u.ID
	u.fieldMap["freeCount"] = u.FreeCount
	u.fieldMap["AddDate"] = u.AddDate
	u.fieldMap["LotteryCount"] = u.LotteryCount
	u.fieldMap["nFreeIndex"] = u.NFreeIndex
	u.fieldMap["gameDict"] = u.GameDict
}

func (u useraccount) clone(db *gorm.DB) useraccount {
	u.useraccountDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u useraccount) replaceDB(db *gorm.DB) useraccount {
	u.useraccountDo.ReplaceDB(db)
	return u
}

type useraccountDo struct{ gen.DO }

type IUseraccountDo interface {
	gen.SubQuery
	Debug() IUseraccountDo
	WithContext(ctx context.Context) IUseraccountDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IUseraccountDo
	WriteDB() IUseraccountDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IUseraccountDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IUseraccountDo
	Not(conds ...gen.Condition) IUseraccountDo
	Or(conds ...gen.Condition) IUseraccountDo
	Select(conds ...field.Expr) IUseraccountDo
	Where(conds ...gen.Condition) IUseraccountDo
	Order(conds ...field.Expr) IUseraccountDo
	Distinct(cols ...field.Expr) IUseraccountDo
	Omit(cols ...field.Expr) IUseraccountDo
	Join(table schema.Tabler, on ...field.Expr) IUseraccountDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IUseraccountDo
	RightJoin(table schema.Tabler, on ...field.Expr) IUseraccountDo
	Group(cols ...field.Expr) IUseraccountDo
	Having(conds ...gen.Condition) IUseraccountDo
	Limit(limit int) IUseraccountDo
	Offset(offset int) IUseraccountDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IUseraccountDo
	Unscoped() IUseraccountDo
	Create(values ...*model.Useraccount) error
	CreateInBatches(values []*model.Useraccount, batchSize int) error
	Save(values ...*model.Useraccount) error
	First() (*model.Useraccount, error)
	Take() (*model.Useraccount, error)
	Last() (*model.Useraccount, error)
	Find() ([]*model.Useraccount, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Useraccount, err error)
	FindInBatches(result *[]*model.Useraccount, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Useraccount) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IUseraccountDo
	Assign(attrs ...field.AssignExpr) IUseraccountDo
	Joins(fields ...field.RelationField) IUseraccountDo
	Preload(fields ...field.RelationField) IUseraccountDo
	FirstOrInit() (*model.Useraccount, error)
	FirstOrCreate() (*model.Useraccount, error)
	FindByPage(offset int, limit int) (result []*model.Useraccount, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IUseraccountDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (u useraccountDo) Debug() IUseraccountDo {
	return u.withDO(u.DO.Debug())
}

func (u useraccountDo) WithContext(ctx context.Context) IUseraccountDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u useraccountDo) ReadDB() IUseraccountDo {
	return u.Clauses(dbresolver.Read)
}

func (u useraccountDo) WriteDB() IUseraccountDo {
	return u.Clauses(dbresolver.Write)
}

func (u useraccountDo) Session(config *gorm.Session) IUseraccountDo {
	return u.withDO(u.DO.Session(config))
}

func (u useraccountDo) Clauses(conds ...clause.Expression) IUseraccountDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u useraccountDo) Returning(value interface{}, columns ...string) IUseraccountDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u useraccountDo) Not(conds ...gen.Condition) IUseraccountDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u useraccountDo) Or(conds ...gen.Condition) IUseraccountDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u useraccountDo) Select(conds ...field.Expr) IUseraccountDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u useraccountDo) Where(conds ...gen.Condition) IUseraccountDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u useraccountDo) Order(conds ...field.Expr) IUseraccountDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u useraccountDo) Distinct(cols ...field.Expr) IUseraccountDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u useraccountDo) Omit(cols ...field.Expr) IUseraccountDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u useraccountDo) Join(table schema.Tabler, on ...field.Expr) IUseraccountDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u useraccountDo) LeftJoin(table schema.Tabler, on ...field.Expr) IUseraccountDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u useraccountDo) RightJoin(table schema.Tabler, on ...field.Expr) IUseraccountDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u useraccountDo) Group(cols ...field.Expr) IUseraccountDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u useraccountDo) Having(conds ...gen.Condition) IUseraccountDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u useraccountDo) Limit(limit int) IUseraccountDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u useraccountDo) Offset(offset int) IUseraccountDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u useraccountDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IUseraccountDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u useraccountDo) Unscoped() IUseraccountDo {
	return u.withDO(u.DO.Unscoped())
}

func (u useraccountDo) Create(values ...*model.Useraccount) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u useraccountDo) CreateInBatches(values []*model.Useraccount, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u useraccountDo) Save(values ...*model.Useraccount) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u useraccountDo) First() (*model.Useraccount, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Useraccount), nil
	}
}

func (u useraccountDo) Take() (*model.Useraccount, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Useraccount), nil
	}
}

func (u useraccountDo) Last() (*model.Useraccount, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Useraccount), nil
	}
}

func (u useraccountDo) Find() ([]*model.Useraccount, error) {
	result, err := u.DO.Find()
	return result.([]*model.Useraccount), err
}

func (u useraccountDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Useraccount, err error) {
	buf := make([]*model.Useraccount, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u useraccountDo) FindInBatches(result *[]*model.Useraccount, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u useraccountDo) Attrs(attrs ...field.AssignExpr) IUseraccountDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u useraccountDo) Assign(attrs ...field.AssignExpr) IUseraccountDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u useraccountDo) Joins(fields ...field.RelationField) IUseraccountDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u useraccountDo) Preload(fields ...field.RelationField) IUseraccountDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u useraccountDo) FirstOrInit() (*model.Useraccount, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Useraccount), nil
	}
}

func (u useraccountDo) FirstOrCreate() (*model.Useraccount, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Useraccount), nil
	}
}

func (u useraccountDo) FindByPage(offset int, limit int) (result []*model.Useraccount, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u useraccountDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u useraccountDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u useraccountDo) Delete(models ...*model.Useraccount) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *useraccountDo) withDO(do gen.Dao) *useraccountDo {
	u.DO = *do.(*gen.DO)
	return u
}
